# Generated by Django 3.2.3 on 2021-05-17 09:46

import backend.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.SlugField(validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('orderdate', models.DateField(null=True)),
                ('orderquantity', models.IntegerField(validators=[backend.validators.qty_validation])),
                ('sales', models.DecimalField(decimal_places=2, max_digits=8, validators=[backend.validators.sales_validation])),
                ('shipmode', models.CharField(max_length=100, validators=[backend.validators.ship_validation])),
                ('profit', models.DecimalField(decimal_places=2, max_digits=8, validators=[backend.validators.profit_validation])),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=8, validators=[backend.validators.profit_validation])),
                ('customername', models.CharField(max_length=100)),
                ('customersegment', models.CharField(max_length=100)),
                ('productcategory', models.CharField(max_length=100)),
            ],
        ),
    ]
