# Generated by Django 3.2.3 on 2021-05-18 10:45

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='sales',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[backend.validators.sales_validation]),
        ),
    ]
